line-length = 100

[lint]
select = ["ALL"]
ignore = ["D203", "D213", "COM812", "TRY003" , "EM101", "EM102"]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101", "S311"]


[format]
indent-style = "space"
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 100
