line-length = 100

[lint]
select = ["ALL"]
ignore = ["D203", "D213"]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101"]


[format]
indent-style = "space"
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 100
